

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

hello:
    pattern:  /hello/{name}/{price}
    defaults: { _controller: MR12MainBundle:Hello:index }
    
products:
    pattern:  /products/
    defaults: { _controller: MR12MainBundle:Product:index }
    
product_delete:
    pattern: /products/delete/{id}
    defaults: { _controller: MR12MainBundle:Product:delete }
    
invoices:
    pattern: /products/invoice/
    defaults: { _controller: MR12MainBundle:Invoice:index }
    
invoice_add:
    pattern: /products/invoice/add/{product_id}
    defaults: { _controller: MR12MainBundle:Invoice:add }