<?php
/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
return function($container) {
    $instance = new \MR12\MainBundle\Controller\InvoiceController();
    return $instance;
};
